FROM python:3.8-slim

RUN pip config set global.index-url https://mirrors.bfsu.edu.cn/pypi/web/simple

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -U 'ray[all]==2.2.0'

RUN apt-get update && apt-get install -y openjdk-11-jdk maven git  && rm -rf /var/lib/apt/lists/*